package com.elitetech_inc.ensarkbank.common.enums;

public enum NotificationType {
    TRANSACTION_SUCCESS,
    TRANSACTION_FAILED,
    DEPOSIT,
    WITHDRAW,
    TRANSFER,
    ACCOUNT_CREATED,
    ACCOUNT_SUSPENDED,
    ACCOUNT_STATUS_CHANGED,
    CARD_APPLICATION,
    CARD_STATUS_CHANGED,
    LOAN_APPLICATION,
    LOAN_APPROVED,
    LOAN_REJECTED,
    KYC_SUBMITTED,
    KYC_VERIFIED,
    KYC_REJECTED,
    CUSTOMER_REGISTERED,
    GENERAL
}
