spring.application.name=bank-management-system

# Database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bank_management?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.port=8085

# File Uploads
image.upload.dir=D:/SpringBoot/assets/images/
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Email
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=emonsarkar.emo683
#spring.mail.password=imdt enbz phon hrqo
#spring.mail.protocol=smtp
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000

# JWT
#jwt.secret=683OrRNRpi677482ta57R8662OI143eM
#jwt.expiration=900000
#jwt.verification-expiration=3600000
#jwt.reset-expiration=900000

# Frontend
#app.frontend-url=http://localhost:4200
